### ISSUE TITLE
As a user, I should be able to fill out the form on the create page and click submit, which will take me to the poster page corresponding with and displaying the quote I made

### ISSUE THREAD

**Issue by AlexaVanSchaardenburg** [rachelsoae/stretch-fe#16]

**Comment by AlexaVanSchaardenburg** [comment]
**ACCEPTANCE CRITERIA**
- [x] - [ ] OPTIONAL (but fun) When a user selects which quote type they are creating the form background turns to the accent color of that type (see the wireframe)
- [x] A user can add text inputs to both other form areas
- [x] when a user clicks submit they are rerouted to the appropriate page and the quote they created is displayed
- [ ] The favorite button still works

**Comment by rachelsoae** [comment]
Favorite button yet to be added, but form is fully functional
