### ISSUE TITLE
As a user I should be able to favorite a randomly generated quote

### ISSUE THREAD

**Issue by AlexaVanSchaardenburg** [rachelsoae/stretch-fe#19]

**Comment by AlexaVanSchaardenburg** [comment]
**Acceptance Criteria**

- [x] When the heart button is clicked the quote and poster will be added to the favorites data set
- [ ] The user will be rerouted tot the favorites page, where the favorited quote will be displayed

**Comment by rachelsoae** [comment]
Decided against immediate re-routing, but we should add a message that confirms the poster has been added as a favorite. Adding as a separate issue.
